[window.padding]
x = 10
y = 7

[font]
size = 9.0

[font.normal]
family = "Fira Code"

[font.bold]
family = "Fira Code"
style = "Bold"

[font.italic]
family = "Fira Code"
style = "Italic"

[font.bold_italic]
family = "Fira Code"
style = "Bold Italic"

# Default colors
[colors.primary]
background = '0x25242c'
foreground = '0xc2bcc6'

# Cursor is reversed primary
[colors.cursor]
text = '0x25242c'
cursor = '0xc2bcc6'

# Normal colors
[colors.normal]
black =   '0x1c1a21'
red =     '0xf55897'
green =   '0x34c294'
yellow =  '0xffaa49'
blue =    '0x5867f5'
magenta = '0xb05c90'
cyan =    '0x17a5cf'
white =   '0x9a8ea6'

# Bright colors
[colors.bright]
black =   '0x6d6a66'
red =     '0xf77bb2'
green =   '0x5cbf9e'
yellow =  '0xe8b882'
blue =    '0x6b74c7'
magenta = '0xd97ec0'
cyan =    '0x86eef0'
white =   '0xc4b5d4'
